id: b9ebb1f7-364c-4fa3-8cfb-6e54a1218ea0
version: 28
vcShouldKeepItemLegacyProdMachine: false
name: POV Pack Installer
description: This designed to handle installing a series of packs at a time including
  logic for timeouts due long run content install
tags:
- PoV
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: ce093bec-358c-488b-86e1-db074c4d0f7d
    type: start
    task:
      id: ce093bec-358c-488b-86e1-db074c4d0f7d
      version: -1
      name: ""
      iscommand: false
      brand: ""
      playbooktaskmissingcomponent: null
      istaskmissingcomponenterrordismissed: false
    nexttasks:
      '#none#':
      - "10"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 30edf6bf-7343-45de-ad62-35714fa93646
    type: title
    task:
      id: 30edf6bf-7343-45de-ad62-35714fa93646
      version: -1
      name: Check If Packs are Installed
      type: title
      iscommand: false
      brand: ""
      playbooktaskmissingcomponent: null
      istaskmissingcomponenterrordismissed: false
    nexttasks:
      '#none#':
      - "9"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 405
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: b99136a1-7ccd-47f3-b445-7de01cff4356
    type: title
    task:
      id: b99136a1-7ccd-47f3-b445-7de01cff4356
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      playbooktaskmissingcomponent: null
      istaskmissingcomponenterrordismissed: false
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 760
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: 52d10ccb-9355-4222-946c-5214073aaffa
    type: playbook
    task:
      id: 52d10ccb-9355-4222-946c-5214073aaffa
      version: -1
      name: POV Wait For Pack install
      description: This is playbook checks the market place for a pack that was installed
        and exits when it is installed.
      playbookName: POV Wait For Pack install
      type: playbook
      iscommand: false
      brand: ""
      playbooktaskmissingcomponent: null
      istaskmissingcomponenterrordismissed: false
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      debug:
        simple: ${inputs.debug}
      pack_id:
        simple: ${inputs.pack_id}
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 60
      max: 100
      forEach: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 575
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: 774ffa5e-a31c-4b9e-8a83-c7512f96d1d7
    type: regular
    task:
      id: 774ffa5e-a31c-4b9e-8a83-c7512f96d1d7
      version: -1
      name: Install Custom Pack
      scriptName: SOCFWInstallPackZip
      type: regular
      iscommand: false
      brand: ""
      playbooktaskmissingcomponent: null
      istaskmissingcomponenterrordismissed: false
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      debug:
        simple: ${inputs.debug}
      file_url:
        simple: ${inputs.pack_url}
      skip_validation:
        simple: "False"
      skip_verify:
        simple: "True"
    separatecontext: false
    continueonerror: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 220
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 770,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: pack_url
  value:
    simple: ${ConfigurationSetup.CustomPacks.packurl}
  required: true
  description: URL to use for install pack zipfile.
  playbookInputQuery: null
- key: pack_id
  value:
    simple: ${ConfigurationSetup.CustomPacks.packid}
  required: true
  description: 'Pack ids to check to see if pack was installed.  '
  playbookInputQuery: null
- key: debug
  value:
    simple: "false"
  required: false
  description: ""
  playbookInputQuery: null
inputSections:
- inputs:
  - pack_url
  - pack_id
  - debug
  name: General (Inputs group)
  description: Generic group for inputs
outputSections:
- outputs: []
  name: General (Outputs group)
  description: Generic group for outputs
outputs: []
dirtyInputs: true
adopted: true
